import { z } from 'zod'

import type { ResearchResult } from '@/types/research'

/**
 * Validation for the one payload the browser hands back to the server.
 *
 * `createDraftFromResearch` takes a whole `ResearchResult` as an argument. A
 * server action is a public POST endpoint, so the client is under no obligation
 * to send back what the server returned — it may send anything, at any size.
 * Every field of it then flows into the Claude prompt: `summary`, each source's
 * title, url and snippet, the pain points, the keywords and the full deep
 * report. Unbounded, that is cost amplification on a metered model call, on top
 * of the injection surface the prompt fence already guards.
 *
 * **These ceilings reject; they do not truncate.** A deep report is primary
 * material the writer quotes from, and slicing one at an arbitrary character
 * would corrupt a legitimate draft silently — a far worse outcome than an error
 * message. So every ceiling sits roughly an order of magnitude above what the
 * research pipeline itself produces: nothing this application generates can
 * reach one, and anything that does was not generated by it.
 *
 * `topic` and `brief` are the exception and are handled by the caller: they are
 * typed by a human into a form, and `startResearch` already slices both rather
 * than refusing them. Clamping there is the established behaviour and matches
 * what the person at the keyboard expects.
 */

/**
 * The two human-typed fields, clamped rather than refused. They live here so
 * that `startResearch`, `pollResearchJob`, `createDraftFromResearch` and the
 * older /research action all clamp to the same number — the caps used to be
 * module-local to one server-action file, which is why two callers had none.
 */
export const MAX_TOPIC_LENGTH = 300
export const MAX_BRIEF_LENGTH = 2_000

/** The synthesised research summary — a few paragraphs in practice. */
const MAX_SUMMARY_CHARS = 20_000
/** Full text of an agentic Exa Research run, quoted verbatim to the writer. */
const MAX_DEEP_REPORT_CHARS = 200_000
/** Exa returns at most a couple of dozen; the prompt renders every one. */
const MAX_SOURCES = 60
const MAX_SOURCE_TITLE_CHARS = 500
const MAX_SOURCE_URL_CHARS = 2_000
const MAX_SOURCE_SNIPPET_CHARS = 5_000
/** Not normalised on purpose (see ResearchSource), so bound it as free text. */
const MAX_SOURCE_DATE_CHARS = 100
const MAX_CONTEXT_ENTRIES = 50
const MAX_KEYWORD_CHARS = 200
const MAX_PAIN_POINT_CHARS = 500

const sourceSchema = z.object({
  title: z.string().max(MAX_SOURCE_TITLE_CHARS),
  url: z.string().max(MAX_SOURCE_URL_CHARS),
  snippet: z.string().max(MAX_SOURCE_SNIPPET_CHARS),
  publishedDate: z.string().max(MAX_SOURCE_DATE_CHARS).optional(),
})

const researchResultSchema = z.object({
  summary: z.string().max(MAX_SUMMARY_CHARS),
  sources: z.array(sourceSchema).max(MAX_SOURCES),
  suggestedContext: z.object({
    keywords: z.array(z.string().max(MAX_KEYWORD_CHARS)).max(MAX_CONTEXT_ENTRIES),
    pain_points: z.array(z.string().max(MAX_PAIN_POINT_CHARS)).max(MAX_CONTEXT_ENTRIES),
  }),
  deepReport: z.string().max(MAX_DEEP_REPORT_CHARS).optional(),
})

/**
 * Thrown for a payload that is not a `ResearchResult` or that exceeds a
 * ceiling. Separate from the pipeline's own failures so the caller can report
 * it as a rejected request rather than a broken generation.
 */
export class ResearchInputError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ResearchInputError'
  }
}

/**
 * Parse a client-supplied research payload, or throw `ResearchInputError`.
 *
 * Unknown keys are stripped rather than refused: the shape is versioned by
 * deployment, and a stale tab posting a field this build no longer reads should
 * not be an error. What matters is that nothing unrecognised reaches the
 * prompt, and `z.object` already guarantees that.
 */
export function parseResearchResult(input: unknown): ResearchResult {
  const parsed = researchResultSchema.safeParse(input)
  if (!parsed.success) {
    const first = parsed.error.issues[0]
    const where = first?.path.length ? first.path.join('.') : 'payload'
    throw new ResearchInputError(
      `The research payload was rejected at "${where}": ${first?.message ?? 'invalid'}.`,
    )
  }
  return parsed.data
}

export const RESEARCH_INPUT_LIMITS = {
  summary: MAX_SUMMARY_CHARS,
  deepReport: MAX_DEEP_REPORT_CHARS,
  sources: MAX_SOURCES,
  sourceTitle: MAX_SOURCE_TITLE_CHARS,
  sourceUrl: MAX_SOURCE_URL_CHARS,
  sourceSnippet: MAX_SOURCE_SNIPPET_CHARS,
  sourceDate: MAX_SOURCE_DATE_CHARS,
  contextEntries: MAX_CONTEXT_ENTRIES,
  keyword: MAX_KEYWORD_CHARS,
  painPoint: MAX_PAIN_POINT_CHARS,
} as const
