import { defineType, defineField, defineArrayMember } from 'sanity'
import { StackCompactIcon } from '@sanity/icons'
import { slugify } from '@/lib/utils'

/**
 * An ordered reading path across existing articles — a "playlist".
 *
 * Why a document and not a field on `article`: every other organising axis the
 * site has (`categories`, `intelligenceTier`, `contentType`, `personas`,
 * `methodologyPillars`) is a *facet* — an unordered attribute of one piece. A
 * series has an order, a title, an argument and a state, none of which fit on
 * the members.
 *
 * **The array position in `entries` IS the part number.** No part number is
 * typed anywhere, on purpose: a `part: 3` on each article is the same fact in
 * N places, free to disagree, and inserting a part means renumbering the rest
 * by hand. Same rule as prices (`src/lib/offering.ts`) and publication dates
 * (`src/lib/published-at.ts`) — one source, derived everywhere else.
 */
export const series = defineType({
  name: 'series',
  title: 'Series',
  type: 'document',
  icon: StackCompactIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 64,
        // Same word-boundary truncation as `article`, so the two URL families
        // are generated by one rule rather than two that drift.
        slugify: (input) => slugify(input, 64),
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'standfirst',
      title: 'Standfirst',
      description:
        'The argument of the series — why these pieces belong in this order. Not a summary of part one.',
      type: 'text',
      rows: 3,
      validation: (rule) =>
        rule.required().max(240).warning('Keep the standfirst under 240 characters'),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          type: 'string',
          title: 'Alternative Text',
          validation: (rule) => rule.required(),
        }),
      ],
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'In progress — more parts to come', value: 'in-progress' },
          { title: 'Complete', value: 'complete' },
        ],
        layout: 'radio',
      },
      initialValue: 'in-progress',
    }),
    defineField({
      name: 'entries',
      title: 'Parts, in reading order',
      description:
        'Drag to reorder. The position in this list is the part number — there is nothing to type. ' +
        'An article that is still a draft may be added: it holds its slot and the site shows it as "in preparation".',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'reference',
          // WEAK, and it has to be. Two reasons, both load-bearing:
          //
          //   1. A published series may point at parts that are still drafts —
          //      that is the whole point of laying an arc out in advance. See
          //      researchRun.articles[] for the same lesson learned the hard way.
          //   2. Strong references block deleting a member article, so
          //      unpublishArticle() would have to sweep `entries[_ref=="..."]`
          //      — and unsetting an array member COLLAPSES the array, silently
          //      promoting Part 3 to Part 2. Stable part numbers are the one
          //      invariant this feature has; a weak ref just stops resolving
          //      and the slot survives.
          weak: true,
          to: [{ type: 'article' }],
        }),
      ],
      validation: (rule) =>
        rule
          .required()
          .min(2)
          .error('A series needs at least two parts.')
          // NOT rule.unique(). It compares array members with a key-count guard
          // before ignoring _key, and a reference Studio writes to a draft-only
          // document carries extra props (_weak, _strengthenOnPublish) — so the
          // counts differ, the comparison short-circuits, and the duplicate goes
          // undetected. Referencing drafts is routine here, so that case is the
          // normal one rather than the exotic one.
          .custom((entries?: Array<{ _key?: string; _ref?: string }>) => {
            if (!Array.isArray(entries)) return true
            const seen = new Set<string>()
            const duplicates: string[] = []
            for (const entry of entries) {
              const ref = entry?._ref
              if (!ref) continue
              if (seen.has(ref)) {
                if (entry._key) duplicates.push(entry._key)
              } else {
                seen.add(ref)
              }
            }
            if (duplicates.length === 0) return true
            return {
              message:
                'An article can only appear once in a series — its position in this list is its part number.',
              paths: duplicates.map((key) => [{ _key: key }]),
            }
          }),
    }),
    defineField({
      name: 'categories',
      title: 'Categories',
      description: 'Optional. Used to describe the series on the index, not to gate anything.',
      type: 'array',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'category' }] })],
    }),
    defineField({
      name: 'personas',
      title: 'Target Personas',
      description: 'Which decision-makers is this reading path most useful to?',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      options: {
        list: [
          { title: 'Compliance Clara (Legal/Compliance)', value: 'clara' },
          { title: 'Industrial Ian (Operations/Supply Chain)', value: 'ian' },
          { title: 'Sovereign Sofia (Policy/Analysis)', value: 'sofia' },
          { title: 'Global Citizen (General Public)', value: 'citizen' },
          { title: 'Transatlantic Troy (Founder/CEO, US–EU Market Entry)', value: 'troy' },
        ],
      },
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      description: 'Show this series first on the index.',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'displayOrder',
      title: 'Display order',
      description: 'Lower sorts first. Leave blank to fall back to alphabetical.',
      type: 'number',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'object',
      fields: [
        defineField({
          name: 'metaTitle',
          title: 'Meta Title',
          type: 'string',
          description: 'Override the default title for search engines',
        }),
        defineField({
          name: 'metaDescription',
          title: 'Meta Description',
          type: 'text',
          rows: 3,
          validation: (rule) => rule.max(160).warning('Keep meta descriptions under 160 characters'),
        }),
      ],
    }),
  ],
  orderings: [
    {
      title: 'Display order',
      name: 'displayOrderAsc',
      by: [
        { field: 'featured', direction: 'desc' },
        { field: 'displayOrder', direction: 'asc' },
        { field: 'title', direction: 'asc' },
      ],
    },
    { title: 'Title, A–Z', name: 'titleAsc', by: [{ field: 'title', direction: 'asc' }] },
  ],
  preview: {
    select: {
      title: 'title',
      status: 'status',
      media: 'coverImage',
      entries: 'entries',
    },
    prepare({ title, status, media, entries }) {
      const count = Array.isArray(entries) ? entries.length : 0
      const state = status === 'complete' ? 'complete' : 'in progress'
      return {
        title,
        subtitle: `${count} ${count === 1 ? 'part' : 'parts'} · ${state}`,
        media,
      }
    },
  },
})
