import type { AssessmentQuestionV2, ConditionExpression } from '../types'

/**
 * The GDPR-for-AI overlay's questions (§11.2).
 *
 * Three rules shape this file, and all three are §11's rather than §7's.
 *
 * **None of these may block the AI Act result.** That is a Phase 7 exit
 * criterion, and it is structural here rather than a matter of care: no question
 * below is `required`, so `isFinished` never waits on one, and none is
 * `classification_decisive`, so §9.5's confidence rule cannot be reached through
 * a data-protection answer. A reader who wants their AI Act position and nothing
 * else can walk past the whole section.
 *
 * **They open only where personal data may be involved** (§11.1) — which
 * includes "possibly" and includes the explicit unknown. `personal_data_use` is
 * the one triage question whose "not sure" v1 resolved to "no", and resolving it
 * that way here would silently close the overlay on exactly the readers most
 * likely to need it.
 *
 * **They are about AI, not about data protection generally.** §11.2's list is
 * short on purpose: source, basis, significant automated decisions, genuine
 * human intervention, DPIA, controller/processor, transfers, supplier retention
 * and model-improvement use, and whether a person's data can be found again.
 * Everything else a GDPR audit would ask is out of scope and stays out —
 * "not a complete GDPR audit" has to be true of the questions before it can be
 * true of the notice.
 */

/** §11.1: yes, possibly, or an explicit unknown. Never "no". */
export const PERSONAL_DATA_POSSIBLE: ConditionExpression = {
  any: [
    { questionId: 'personal_data_use', includesAny: ['yes', 'possibly'] },
    { questionId: 'personal_data_use', state: 'unknown' },
  ],
}

const SECTION = 'Data protection'

export const GDPR_QUESTIONS: AssessmentQuestionV2[] = [
  {
    id: 'gdpr_data_categories',
    section: SECTION,
    prompt: 'Which of these kinds of data does the system handle?',
    shortPrompt: 'Data categories',
    help:
      'Choose every one that applies. If the system only handles ordinary business contact details and records, choose the last option.',
    whyAsked:
      'Some categories of personal data carry stricter conditions before they may be used at all. Whether any are involved changes what a data-protection review of this system would have to cover.',
    examples: [
      'A recruitment tool holding health information from adjustment requests handles health data.',
      'A tutoring assistant used by under-18s handles children’s data.',
    ],
    answerType: 'multi',
    options: [
      { value: 'health', label: 'Health or medical information' },
      { value: 'biometric_identification', label: 'Biometric data used to identify someone' },
      {
        value: 'protected_characteristics',
        label: 'Race, ethnicity, religion, politics, trade union membership, sex life or sexual orientation',
      },
      { value: 'criminal_offence', label: 'Criminal offences, convictions or allegations' },
      { value: 'children', label: 'Data about children' },
      { value: 'none_of_these', label: 'None of these — ordinary personal data only' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
    validate: [{ kind: 'maxSelections', value: 5, message: 'Select up to five categories.' }],
  },
  {
    id: 'gdpr_data_source',
    section: SECTION,
    prompt: 'Where does the personal data come from?',
    shortPrompt: 'Data source',
    help: 'Choose every route that applies. Most systems have more than one.',
    whyAsked:
      'What you owe the people in the data depends partly on whether they gave it to you themselves. Data obtained from somewhere else carries an additional duty to tell them you hold it.',
    answerType: 'multi',
    options: [
      { value: 'from_individuals', label: 'From the people themselves' },
      { value: 'from_another_organisation', label: 'From another organisation' },
      { value: 'public_or_scraped', label: 'From public sources, or scraped from the web' },
      { value: 'purchased_dataset', label: 'From a purchased or licensed dataset' },
      { value: 'generated_by_system', label: 'Inferred or generated by the system itself' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
    validate: [{ kind: 'maxSelections', value: 5, message: 'Select up to five sources.' }],
  },
  {
    id: 'gdpr_lawful_basis',
    section: SECTION,
    prompt: 'Has anyone decided, and written down, why you are allowed to use this data?',
    shortPrompt: 'Lawful basis',
    help:
      'Data protection law requires a specific reason for each use of personal data, chosen before the use starts. The question is whether that decision has been made and recorded, not whether it was the right one.',
    whyAsked:
      'This is the single most common gap when an AI system is added to an existing process: the data was collected for one purpose and is now being used for another, and nobody revisited the reason it was allowed.',
    answerType: 'single',
    options: [
      { value: 'reviewed_and_recorded', label: 'Yes — decided and written down' },
      { value: 'identified_not_recorded', label: 'We know what it is, but it is not written down' },
      { value: 'not_reviewed', label: 'No — this has not been looked at for this system' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
  },
  {
    id: 'gdpr_significant_effects',
    section: SECTION,
    prompt: 'Can the system’s output produce a legal or similarly significant effect for a person?',
    shortPrompt: 'Significant effects',
    help:
      'Significant means it changes something real for them — a job, a loan, a place, a price, a benefit, access to a service. Ranking a search result is not; declining an application is.',
    whyAsked:
      'Decisions of that kind, taken without meaningful human involvement, are restricted under data protection law separately from anything the AI Act says. This is where the two regimes most often meet.',
    answerType: 'single',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: {
      all: [
        PERSONAL_DATA_POSSIBLE,
        {
          any: [
            {
              questionId: 'individual_impact',
              includesAny: ['informs_human_decision', 'recommends_ranks_scores', 'determines_outcome'],
            },
            { questionId: 'individual_impact', state: 'unknown' },
          ],
        },
      ],
    },
  },
  {
    id: 'gdpr_human_intervention',
    section: SECTION,
    prompt: 'When the system produces that output, what does a person actually do with it?',
    shortPrompt: 'Human involvement',
    help:
      'Think about what happens on an ordinary day with an ordinary case, not about what the policy says should happen.',
    whyAsked:
      'A review only counts if the reviewer has the authority to reach a different answer, the information to do it, and the time it takes. A sign-off that never changes anything is not human involvement in the sense the law means.',
    answerType: 'single',
    options: [
      {
        value: 'meaningful_review',
        label: 'Someone reviews it and can, and sometimes does, decide otherwise',
      },
      {
        value: 'nominal_review',
        label: 'Someone signs it off, but in practice the output stands',
      },
      { value: 'no_review', label: 'Nobody reviews it — the output is acted on directly' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: { questionId: 'gdpr_significant_effects', equals: 'yes' },
  },
  {
    id: 'gdpr_dpia_status',
    section: SECTION,
    prompt: 'Has a data protection impact assessment been done for this system?',
    shortPrompt: 'DPIA',
    help:
      'A DPIA is a written assessment of the risks a processing activity poses to the people in the data, and of what is being done about them. "Considered and not needed" is a valid answer if the reasoning was recorded.',
    whyAsked:
      'Where a system is likely to pose a high risk to people, an assessment is required before it starts — so this is one of the few data-protection questions where the timing matters as much as the substance.',
    answerType: 'single',
    options: [
      { value: 'completed', label: 'Yes — completed' },
      { value: 'in_progress', label: 'In progress' },
      { value: 'considered_not_required', label: 'Considered, and recorded as not required' },
      { value: 'not_considered', label: 'No — this has not been considered' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
  },
  {
    id: 'gdpr_controller_role',
    section: SECTION,
    prompt: 'For this system, does your organisation decide why and how the data is used?',
    shortPrompt: 'Controller or processor',
    help:
      'Deciding the purpose makes you a controller. Doing it only on someone else’s written instructions makes you a processor. Deciding it jointly with another organisation makes you joint controllers.',
    whyAsked:
      'Almost every data-protection duty attaches to the controller. This is the data-protection counterpart of the AI Act role question, and the two answers are not the same: a deployer under the AI Act is very often a controller, but not always.',
    answerType: 'single',
    options: [
      { value: 'controller', label: 'Yes — we decide' },
      { value: 'processor', label: 'No — we act on another organisation’s instructions' },
      { value: 'joint', label: 'We decide jointly with another organisation' },
      { value: 'not_established', label: 'This has not been established' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
  },
  {
    id: 'gdpr_transfers',
    section: SECTION,
    prompt: 'Does the personal data leave the UK or the European Economic Area?',
    shortPrompt: 'Transfers',
    help:
      'Including where it is only stored or processed abroad. Most AI services run somewhere — if you do not know where, that is the answer to give.',
    whyAsked:
      'Sending personal data outside the UK or the EEA needs its own safeguard, and with a hosted AI service the transfer is usually a property of the supplier rather than a decision you made.',
    answerType: 'single',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No — it stays in the UK or the EEA' },
      { value: 'not_established', label: 'This has not been established' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
  },
  {
    id: 'gdpr_supplier_data_use',
    section: SECTION,
    prompt: 'What may your supplier do with the data you put into the system?',
    shortPrompt: 'Supplier data use',
    help:
      'This is usually settled by the contract or the terms of service rather than by a conversation. If you built the system yourself, choose the last option.',
    whyAsked:
      'Whether inputs are retained, and whether they may be used to improve the supplier’s models, is the question most often left unasked when an AI tool is adopted — and the one hardest to undo afterwards.',
    answerType: 'single',
    options: [
      { value: 'excluded_by_terms', label: 'The terms exclude retention and training use' },
      { value: 'retention_only', label: 'Inputs are retained, but not used for training' },
      { value: 'training_permitted', label: 'Inputs may be used to improve the supplier’s models' },
      { value: 'no_supplier', label: 'There is no supplier — we built and run it ourselves' },
    ],
    allowUnknown: true,
    allowNotApplicable: true,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
  },
  {
    id: 'gdpr_subject_requests',
    section: SECTION,
    prompt: 'If someone asked what the system holds about them, could you find it?',
    shortPrompt: 'Data subject requests',
    help:
      'Finding it, correcting it, and deleting it — including anything the system inferred or generated about them, and anything held in logs.',
    whyAsked:
      'People have the right to ask, and the answer has to arrive within a deadline. AI systems are unusually good at holding data in places nobody thinks to look, which is why this is worth checking before someone asks.',
    answerType: 'single',
    options: [
      { value: 'routine', label: 'Yes — there is a route for it and it has been used' },
      { value: 'with_effort', label: 'Probably, but it would take manual work' },
      { value: 'no_route', label: 'No — we would not know where to look' },
    ],
    allowUnknown: true,
    allowNotApplicable: false,
    importance: 'finding_decisive',
    visibleWhen: PERSONAL_DATA_POSSIBLE,
  },
]
