#!/usr/bin/env bash
#
# view-graph.sh — launch the Understand-Anything dashboard for THIS repo.
#
# The dashboard is just a viewer over .understand-anything/knowledge-graph.json
# (already generated by `/understand`). This script does NOT re-analyse code;
# it only opens the viewer. Re-run `/understand` when you want a fresh graph.
#
# Usage:  ./scripts/view-graph.sh        (or:  npm run graph)
# Then open the bookmarkable URL it prints. Press Ctrl+C to stop.

set -euo pipefail

# Repo root = parent of this script's directory.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Stable, bookmarkable URL without committing a secret: the access token is
# generated once and cached in a GITIGNORED local file (per machine), not baked
# into this script. Localhost-only binding is the real guard; the token just
# blocks other local processes from reading the graph/source endpoints.
TOKEN_FILE="$REPO_ROOT/.understand-anything/.dashboard-token"
if [ ! -s "$TOKEN_FILE" ]; then
  node -e "console.log(require('crypto').randomBytes(12).toString('hex'))" > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
fi
export UNDERSTAND_ACCESS_TOKEN="$(tr -d '[:space:]' < "$TOKEN_FILE")"

GRAPH_FILE="$REPO_ROOT/.understand-anything/knowledge-graph.json"
if [ ! -f "$GRAPH_FILE" ]; then
  echo "No knowledge graph found at $GRAPH_FILE"
  echo "Run the /understand command in Claude Code first to generate it."
  exit 1
fi

# Resolve the newest installed plugin version's dashboard package.
PLUGIN_CACHE="$HOME/.claude/plugins/cache/understand-anything/understand-anything"
DASH_DIR="$(ls -d "$PLUGIN_CACHE"/*/packages/dashboard 2>/dev/null | sort -V | tail -1 || true)"
if [ -z "${DASH_DIR:-}" ] || [ ! -d "$DASH_DIR" ]; then
  echo "Could not find the understand-anything dashboard under $PLUGIN_CACHE"
  echo "Is the understand-anything plugin installed?"
  exit 1
fi
PLUGIN_ROOT="$(cd "$DASH_DIR/../.." && pwd)"

# The dashboard imports @understand-anything/core/dist/*.js — make sure it's built.
if [ ! -f "$PLUGIN_ROOT/packages/core/dist/index.js" ]; then
  echo "Building @understand-anything/core (first run only)…"
  ( cd "$PLUGIN_ROOT/packages/core" && node "$PLUGIN_ROOT/node_modules/typescript/bin/tsc" )
fi

PORT="${PORT:-5173}"
echo ""
echo "  Knowledge graph dashboard for: $REPO_ROOT"
echo "  Bookmark this URL: http://127.0.0.1:${PORT}/?token=${UNDERSTAND_ACCESS_TOKEN}"
echo ""

# Do NOT pass --open on the CLI: a bare `--open` opens an untokenised `/` (403s),
# and `--open "/?token=…"` would leak the token into this process's argv (visible
# via `ps`). The dashboard's own vite.config.ts already sets server.open to
# `/?token=${ACCESS_TOKEN}`, computed from the UNDERSTAND_ACCESS_TOKEN env var we
# export above — so Vite auto-opens the correct tokenised URL with the token kept
# in the environment, never on the command line.
cd "$DASH_DIR"
GRAPH_DIR="$REPO_ROOT" exec npx vite --host 127.0.0.1 --port "$PORT"
